server:
  port: 8080

#TODO: figure out why I need this here and in bootstrap.yml
spring:
  application:
    name: testLatticeApp

ribbon:
  ServerListRefreshInterval: 1000

endpoints:
  health:
    sensitive: false
  restart:
    enabled: true
  shutdown:
    enabled: true


---
logging.config: classpath:log4j2-spring-prod.xml
---
spring:
   profiles: test
logging.config: classpath:log4j2-spring.xml
---
spring:
   profiles: devel
logging.config: classpath:log4j2-spring.xml
---
spring:
   profiles: prod
logging.config: classpath:log4j2-spring-prod.xml